[platformio]
default_envs = esp32
; Cambiar a test/06_diagnostico_radar si se desea usar la GUI gráfica diagnostico_radar.py
src_dir = test/05_radar_acustico

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = -O3
