[platformio]
default_envs = esp32
; Directorio a compilar:
src_dir = test/03_test_adc

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
