[platformio]
default_envs = esp32
; Directorio a compilar (Test 05: Radar Acústico Monostático Completo):
src_dir = test/05_radar_acustico

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = -O3
